version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: event-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_logs
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: event-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=event_logs
    volumes:
      - ./output:/app/output
      - ./data/raw:/app/data/raw

volumes:
  db_data:
